name: Deployment backend to production
on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          -
            name: checkout code
            uses: actions/checkout@v2
          -
            name: Docker login
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          -
            name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: ./
              file: ./Dockerfile
              push: true
              tags: techindustry/thrive:${{ github.sha }}
          -
            name: Deploy to the vps
            uses: appleboy/ssh-action@v1.2.1
            with:
              host: ${{ secrets.HOST }}
              username: root
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                docker pull techindustry/thrive:${{ github.sha }}
                docker stop thive
                docker rm thive
                docker run --name thrive -d -e BOT_TOKEN=${{secrets.BOT_TOKEN}} techindustry/thrive:${{ github.sha }}